#!/bin/bash
QCBDIR=~/QCB301
LISTDIR=$QCBDIR/Lists
NUMTOP=200

echo $QCBDIR/MSN2 > .tmpread
echo $QCBDIR/MIG1 >> .tmpread
echo $QCBDIR/RAP1 >> .tmpread

while read -r line
do
    eval $(echo $line | awk '{printf("WORKING=%s",$1)}' )
    ls $WORKING/[rmi]A[0-9]* > .tmpdir
    ls $WORKING/[rmi]Z[0-9]* >> .tmpdir

    while read -r p
    do
        eval $( echo $p | awk '{printf("FILEIN=%s",$1)}' )
        if [[ -s $FILEIN ]] {
            FILEOUT=${FILEIN##*/}
            awk -v num=$NUMTOP 'BEGIN{a = 0; FS="\t"}NR > 1 && $4 != 0 && $5 !=0 && a < num {a=a + 1;print $1}' $FILEIN > $LISTDIR/$FILEOUT\_TOP
        } fi
    done < .tmpdir
    rm -f .tmpdir

done < .tmpread
rm -f .tmpread
