#!/bin/bash
# FOR processing the GALAXY CUFFDIFF files into usable tab separated files.
(head -1 $1 && tail -70000 $1 | sort -k 14 -r -k 10) | awk 'BEGIN{OFS="\t"}NR==1{print $3,$4,$7,$8,$9,$10,$12,$13,$14}NR > 2 && $0 !~/significant/{gsub("\x27","",$0);print $3,$4,$7,$8,$9,$10,$12,$13,$14}' > $2
